name: Linter

on:
  pull_request:
    types: [ opened, reopened, synchronize, edited ]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: CI workflow
    steps:
      - uses: actions/checkout@master

      - uses: marian-code/python-lint-annotate@v3